import enum


class TWIPR_ErrorCode(enum.IntEnum):
    TWIPR_ERROR_NONE = 0
    TWIPR_ERROR_CRITICAL = 1
    TWIPR_ERROR_WARNING = 2

class TWIPR_SupervisorErrorCodes(enum.IntEnum):
    TWIPR_SUPERVISOR_NONE = 0,
    TWIPR_SUPERVISOR_STUCK = 1,
    TWIPR_SUPERVISOR_WHEEL_SPEED = 2,
    TWIPR_SUPERVISOR_MANUAL_STOP = 3,
    TWIPR_SUPERVISOR_MOTOR_TIMEOUT = 4,
    TWIPR_FIRMWARE_ERROR_RACE_CONDITION = 5,
    TWIPR_SUPERVISOR_ERROR_INTEGRATOR_OVERRUN = 6,
    TWIPR_SUPERVISOR_MOTOR_RACECONDITION = 7,