/*
 * board.h
 *
 *  Created on: Apr 5, 2022
 *      Author: Dustin Lehmann
 */

#ifndef BOARD_CONFIG_H_
#define BOARD_CONFIG_H_

#include "stm32h7xx_hal.h"

#define CORE_BOARD_REV_1

#ifdef CORE_BOARD_REV_1
/* Communication Interfaces */
/* CM4 <-> STM32 UART */
#define CORE_INTERFACE_UART_CM4 USART2
#define CORE_INTERFACE_UART_CM4_BAUD 115200

/* ===== I2C Addresses ===== */

/* EEPROM CORE */
#define CORE_BOARD_I2C_ADDRESS_CORE_EEPROM 0xA0

/* EEPROM USER */
#define CORE_BOARD_I2C_ADDRESS_USER_EEPROM 0xA2

/* ===== GPIO PINS ===== */

/* User LED */
#define CORE_BOARD_ACT_LED_PORT GPIOD
#define CORE_BOARD_ACT_LED_PIN GPIO_PIN_11

#define CORE_BOARD_LED_1_PORT GPIOE
#define CORE_BOARD_LED_1_PIN GPIO_PIN_15

#define CORE_BOARD_LED_2_PORT GPIOE
#define CORE_BOARD_LED_2_PIN GPIO_PIN_10

/* Power Out */
#define CORE_BOARD_GPIO_POWER_OUT_SWITCH_PORT GPIOD
#define CORE_BOARD_GPIO_POWER_OUT_SWITCH_PIN GPIO_PIN_12

/* Chip Select IMU */
#define CORE_BOARD_GPIO_CS_IMU_PORT GPIOB
#define CORE_BOARD_GPIO_CS_IMU_PIN GPIO_PIN_12

/* Chip Select Flash */
#define CORE_BOARD_GPIO_CS_FLASH_PORT GPIOD
#define CORE_BOARD_GPIO_CS_FLASH_PIN GPIO_PIN_14

/* External Chip Select 1 */
#define CORE_BOARD_GPIO_CS_EXT_1_PORT  GPIOD
#define CORE_BOARD_GPIO_CS_EXT_1_PIN GPIO_PIN_3

/* External Chip Select 2 */
#define CORE_BOARD_GPIO_CS_EXT_2_PORT GPIOD
#define CORE_BOARD_GPIO_CS_EXT_2_PIN GPIO_PIN_13

/* External Button */
#define CORE_BOARD_GPIO_EXT_BUTTON_PORT GPIOE
#define CORE_BOARD_GPIO_EXT_BUTTON_PIN GPIO_PIN_2

/* IMU Interrupt */
#define CORE_BOARD_GPIO_IMU_INT_PORT GPIOD
#define CORE_BOARD_GPIO_IMU_INT_PIN GPIO_PIN_10

/* CM4 Interrupts */
#define CORE_BOARD_GPIO_CM4_INT_0_PORT GPIOB
#define CORE_BOARD_GPIO_CM4_INT_0_PIN GPIO_PIN_2

#define CORE_BOARD_GPIO_CM4_INT_1_PORT GPIOE
#define CORE_BOARD_GPIO_CM4_INT_1_PIN GPIO_PIN_8

#define CORE_BOARD_GPIO_CM4_INT_2_PORT GPIOE
#define CORE_BOARD_GPIO_CM4_INT_2_PIN GPIO_PIN_7

/* Detect PG CM4 */
#define CORE_BOARD_GPIO_CM4_PG_PORT GPIOC
#define CORE_BOARD_GPIO_CM4_PG_PIN GPIO_PIN_14

/* Enable CM4 */
#define CORE_BOARD_GPIO_CM4_EN_PORT GPIOC
#define CORE_BOARD_GPIO_CM4_EN_PIN GPIO_PIN_4

/* Detect USB */
#define CORE_BOARD_GPIO_USB_DETECT_PORT GPIOC
#define CORE_BOARD_GPIO_USB_DETECT_PIN GPIO_PIN_8

#endif

#endif /* BOARD_CONFIG_H_ */
