/*
 * registers.h
 *
 *  Created on: Jul 10, 2022
 *      Author: Dustin Lehmann
 */

#ifndef REGISTERS_H_
#define REGISTERS_H_

extern uint8_t firmware_registers[255];

#define REG_COMMAND							0x05

#define REG_CM4_MODE						0x0B
#define REG_CM4_ENABLE						0x0C
#define REG_OUT_5V_ENABLE					0x0D
#define REG_DETECT_SD						0x0E
#define REG_DETECT_USB						0x0F
#define REG_BUTTON_INTERN					0x10
#define REG_BUTTON_EXTERN					0x11
#define REG_V_POWER_0						0x12
#define REG_V_POWER_1						0x13
#define REG_V_POWER_2						0x14
#define REG_V_POWER_3						0x15
#define REG_V_REG_0							0x16
#define REG_V_REG_1							0x17
#define REG_V_REG_2							0x18
#define REG_V_REG_3							0x19

#define REG_ERROR_LED_CONFIG				0x1C
#define REG_ERROR_LED_DATA					0x1D
#define REG_ERROR_LED_BLINKING_TIME			0x1E
#define REG_ERROR_LED_BLINKING_COUNTER		0x1F

#define REG_STATUS_RGB_LED_1_CONFIG			0x20
#define REG_STATUS_RGB_LED_1_RED			0x21
#define REG_STATUS_RGB_LED_1_GREEN			0x22
#define REG_STATUS_RGB_LED_1_BLUE			0x23
#define REG_STATUS_RGB_LED_1_BLINK_TIME		0x24
#define REG_STATUS_RGB_LED_1_BLINK_COUNTER	0x25

#define REG_STATUS_RGB_LED_2_CONFIG			0x26
#define REG_STATUS_RGB_LED_2_RED			0x27
#define REG_STATUS_RGB_LED_2_GREEN			0x28
#define REG_STATUS_RGB_LED_2_BLUE			0x29
#define REG_STATUS_RGB_LED_2_BLINK_TIME		0x2A
#define REG_STATUS_RGB_LED_2_BLINK_COUNTER	0x2B

#define REG_STATUS_RGB_LED_3_CONFIG			0x2C
#define REG_STATUS_RGB_LED_3_RED			0x2D
#define REG_STATUS_RGB_LED_3_GREEN			0x2E
#define REG_STATUS_RGB_LED_3_BLUE			0x2F
#define REG_STATUS_RGB_LED_3_BLINK_TIME		0x30
#define REG_STATUS_RGB_LED_3_BLINK_COUNTER	0x31

#define REG_BUZZER_CONFIG					0x33
#define REG_BUZZER_DATA						0x34
#define REG_BUZZER_FREQ						0x35
#define REG_BUZZER_TIMER					0x36
#define REG_BUZZER_BLINK_TIME				0x37
#define REG_BUZZER_BLINK_COUNTER			0x38

#define REG_EXTERNAL_RGB_CONFIG				0x40
#define REG_EXTERNAL_RGB_GLOBAL_RED			0x41
#define REG_EXTERNAL_RGB_GLOBAL_GREEN		0x42
#define REG_EXTERNAL_RGB_GLOBAL_BLUE		0x43
#define REG_EXTERNAL_RGB_GLOBAL_BLINK_TIME	0x44
#define REG_EXTERNAL_RGB_GLOBAL_BLINK_CNT	0x45

#define REG_EXTERNAL_RGB_LED_1_CONFIG		0x46
#define REG_EXTERNAL_RGB_LED_1_RED			0x47
#define REG_EXTERNAL_RGB_LED_1_GREEN		0x48
#define REG_EXTERNAL_RGB_LED_1_BLUE			0x49
#define REG_EXTERNAL_RGB_LED_1_BLINK_TIME	0x4A
#define REG_EXTERNAL_RGB_LED_1_BLINK_CNT	0x4B

#define REG_EXTERNAL_RGB_LED_2_CONFIG		0x4C
#define REG_EXTERNAL_RGB_LED_2_RED			0x4D
#define REG_EXTERNAL_RGB_LED_2_GREEN		0x4E
#define REG_EXTERNAL_RGB_LED_2_BLUE			0x4F
#define REG_EXTERNAL_RGB_LED_2_BLINK_TIME	0x50
#define REG_EXTERNAL_RGB_LED_2_BLINK_CNT	0x51

#define REG_EXTERNAL_RGB_LED_3_CONFIG		0x52
#define REG_EXTERNAL_RGB_LED_3_RED			0x53
#define REG_EXTERNAL_RGB_LED_3_GREEN		0x54
#define REG_EXTERNAL_RGB_LED_3_BLUE			0x55
#define REG_EXTERNAL_RGB_LED_3_BLINK_TIME	0x56
#define REG_EXTERNAL_RGB_LED_3_BLINK_CNT	0x57

#define REG_EXTERNAL_RGB_LED_4_CONFIG		0x58
#define REG_EXTERNAL_RGB_LED_4_RED			0x59
#define REG_EXTERNAL_RGB_LED_4_GREEN		0x5A
#define REG_EXTERNAL_RGB_LED_4_BLUE			0x5B
#define REG_EXTERNAL_RGB_LED_4_BLINK_TIME	0x5C
#define REG_EXTERNAL_RGB_LED_4_BLINK_CNT	0x5D

#define REG_EXTERNAL_RGB_LED_5_CONFIG		0x5E
#define REG_EXTERNAL_RGB_LED_5_RED			0x5F
#define REG_EXTERNAL_RGB_LED_5_GREEN		0x60
#define REG_EXTERNAL_RGB_LED_5_BLUE			0x61
#define REG_EXTERNAL_RGB_LED_5_BLINK_TIME	0x62
#define REG_EXTERNAL_RGB_LED_5_BLINK_CNT	0x63

#define REG_EXTERNAL_RGB_LED_6_CONFIG		0x64
#define REG_EXTERNAL_RGB_LED_6_RED			0x65
#define REG_EXTERNAL_RGB_LED_6_GREEN		0x66
#define REG_EXTERNAL_RGB_LED_6_BLUE			0x67
#define REG_EXTERNAL_RGB_LED_6_BLINK_TIME	0x68
#define REG_EXTERNAL_RGB_LED_6_BLINK_CNT	0x69

#define REG_EXTERNAL_RGB_LED_7_CONFIG		0x6A
#define REG_EXTERNAL_RGB_LED_7_RED			0x6B
#define REG_EXTERNAL_RGB_LED_7_GREEN		0x6C
#define REG_EXTERNAL_RGB_LED_7_BLUE			0x6D
#define REG_EXTERNAL_RGB_LED_7_BLINK_TIME	0x6E
#define REG_EXTERNAL_RGB_LED_7_BLINK_CNT	0x6F

#define REG_EXTERNAL_RGB_LED_8_CONFIG		0x70
#define REG_EXTERNAL_RGB_LED_8_RED			0x71
#define REG_EXTERNAL_RGB_LED_8_GREEN		0x72
#define REG_EXTERNAL_RGB_LED_8_BLUE			0x73
#define REG_EXTERNAL_RGB_LED_8_BLINK_TIME	0x74
#define REG_EXTERNAL_RGB_LED_8_BLINK_CNT	0x75

#define REG_EXTERNAL_RGB_LED_9_CONFIG		0x76
#define REG_EXTERNAL_RGB_LED_9_RED			0x77
#define REG_EXTERNAL_RGB_LED_9_GREEN		0x78
#define REG_EXTERNAL_RGB_LED_9_BLUE			0x79
#define REG_EXTERNAL_RGB_LED_9_BLINK_TIME	0x7A
#define REG_EXTERNAL_RGB_LED_9_BLINK_CNT	0x7B

#define REG_EXTERNAL_RGB_LED_10_CONFIG		0x7C
#define REG_EXTERNAL_RGB_LED_10_RED			0x7D
#define REG_EXTERNAL_RGB_LED_10_GREEN		0x7E
#define REG_EXTERNAL_RGB_LED_10_BLUE		0x7F
#define REG_EXTERNAL_RGB_LED_10_BLINK_TIME	0x80
#define REG_EXTERNAL_RGB_LED_10_BLINK_CNT	0x81

#define REG_EXTERNAL_RGB_LED_11_CONFIG		0x82
#define REG_EXTERNAL_RGB_LED_11_RED			0x83
#define REG_EXTERNAL_RGB_LED_11_GREEN		0x84
#define REG_EXTERNAL_RGB_LED_11_BLUE		0x85
#define REG_EXTERNAL_RGB_LED_11_BLINK_TIME	0x86
#define REG_EXTERNAL_RGB_LED_11_BLINK_CNT	0x87

#define REG_EXTERNAL_RGB_LED_12_CONFIG		0x88
#define REG_EXTERNAL_RGB_LED_12_RED			0x89
#define REG_EXTERNAL_RGB_LED_12_GREEN		0x8A
#define REG_EXTERNAL_RGB_LED_12_BLUE		0x8B
#define REG_EXTERNAL_RGB_LED_12_BLINK_TIME	0x8C
#define REG_EXTERNAL_RGB_LED_12_BLINK_CNT	0x8D

#define REG_EXTERNAL_RGB_LED_13_CONFIG		0x8E
#define REG_EXTERNAL_RGB_LED_13_RED			0x8F
#define REG_EXTERNAL_RGB_LED_13_GREEN		0x90
#define REG_EXTERNAL_RGB_LED_13_BLUE		0x91
#define REG_EXTERNAL_RGB_LED_13_BLINK_TIME	0x92
#define REG_EXTERNAL_RGB_LED_13_BLINK_CNT	0x93

#define REG_EXTERNAL_RGB_LED_14_CONFIG		0x94
#define REG_EXTERNAL_RGB_LED_14_RED			0x95
#define REG_EXTERNAL_RGB_LED_14_GREEN		0x96
#define REG_EXTERNAL_RGB_LED_14_BLUE		0x97
#define REG_EXTERNAL_RGB_LED_14_BLINK_TIME	0x98
#define REG_EXTERNAL_RGB_LED_14_BLINK_CNT	0x99

#define REG_EXTERNAL_RGB_LED_15_CONFIG		0x9A
#define REG_EXTERNAL_RGB_LED_15_RED			0x9B
#define REG_EXTERNAL_RGB_LED_15_GREEN		0x9C
#define REG_EXTERNAL_RGB_LED_15_BLUE		0x9D
#define REG_EXTERNAL_RGB_LED_15_BLINK_TIME	0x9E
#define REG_EXTERNAL_RGB_LED_15_BLINK_CNT	0x9F

#define REG_EXTERNAL_RGB_LED_16_CONFIG		0xA0
#define REG_EXTERNAL_RGB_LED_16_RED			0xA1
#define REG_EXTERNAL_RGB_LED_16_GREEN		0xA2
#define REG_EXTERNAL_RGB_LED_16_BLUE		0xA3
#define REG_EXTERNAL_RGB_LED_16_BLINK_TIME	0xA4
#define REG_EXTERNAL_RGB_LED_16_BLINK_CNT	0xA5





#endif /* REGISTERS_H_ */
